### ISSUE TITLE
Cannot get the watch in the simulator to show something

### ISSUE THREAD

**Issue by JoergHolz** [Telerik-Verified-Plugins/AppleWatch#9]
I tried the demo, thx to Eddy, I can't see anything in the watch simulator. I wrote a small script to load a payload to the watch, and also: I see nothing.

The watch is connected correct, the success callback from applewatch.loadGlance says, everything okay, but no output on the watch.

I'm using Xcode 6.4, the newest cordova on OS X 10.11.

Where is my mistake?

**Comment by EddyVerbruggen** [comment]
This sounds like an issue with the watch and phone not talking to each other. Have you correctly configured the appgroups?

**Comment by andreground** [comment]
Same here @EddyVerbruggen. Can't get anything on the simultator while everything is running fine on real devices.

**Comment by andreground** [comment]
@JoergHolz After double checking code sign settings at all three levels of my app (Phone target, Watch Extension and Watch App) I can confirm @EddyVerbruggen intuition. The Simulator was not talking to the watch simulator due to misconfigurations in code signing. Check your code sign and appgroup settings and everything will then start working.

**Comment by EddyVerbruggen** [comment]
Thanks @andreground for going through the configuration again. It's a pain but it is what it is..
